// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4y8GUukaTd0x8_PVp4npCcvm6dK64C1A',
    appId: '1:818783908000:web:2958100a2b85c75fdb19c5',
    messagingSenderId: '818783908000',
    projectId: 'chatapp-dc078',
    authDomain: 'chatapp-dc078.firebaseapp.com',
    storageBucket: 'chatapp-dc078.firebasestorage.app',
    measurementId: 'G-5M16B9BJG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFve7NKAWxcw4x65MWTqHajqocIoe5FHw',
    appId: '1:818783908000:android:7cc89e516b0ca33edb19c5',
    messagingSenderId: '818783908000',
    projectId: 'chatapp-dc078',
    storageBucket: 'chatapp-dc078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWH15LkIh5YdUtsJLRUOKq7-JHsR0HYxs',
    appId: '1:818783908000:ios:ddb6538a3c16f2f0db19c5',
    messagingSenderId: '818783908000',
    projectId: 'chatapp-dc078',
    storageBucket: 'chatapp-dc078.firebasestorage.app',
    iosBundleId: 'com.example.whatsappNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWH15LkIh5YdUtsJLRUOKq7-JHsR0HYxs',
    appId: '1:818783908000:ios:ddb6538a3c16f2f0db19c5',
    messagingSenderId: '818783908000',
    projectId: 'chatapp-dc078',
    storageBucket: 'chatapp-dc078.firebasestorage.app',
    iosBundleId: 'com.example.whatsappNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4y8GUukaTd0x8_PVp4npCcvm6dK64C1A',
    appId: '1:818783908000:web:9bc378b034416f49db19c5',
    messagingSenderId: '818783908000',
    projectId: 'chatapp-dc078',
    authDomain: 'chatapp-dc078.firebaseapp.com',
    storageBucket: 'chatapp-dc078.firebasestorage.app',
    measurementId: 'G-NLSDBTSNN0',
  );
}
